# travis-ci
os: linux
dist: xenial
lang: generic

before-install: npm install ganache-core && cd node_modules/ganache-core/node_modules/web3-provider-engine && npm install && npm i --global truffle@5.1.20
git:
  quiet: true

cache: npm

install:
  - npm install
  
script: true
